// Command corvus-catalog generates the checked-in tool catalog and event map:
//
//	corvus-catalog -kind tools                       # tools -> stdout
//	corvus-catalog -kind events -event-source <path> # events -> stdout
//
// The tool catalog is generated from the real process-global built-in registry
// (tool.Builtins), so a new built-in that forgets to regenerate fails CI. The
// event map is parsed from internal/event/event.go's Kind constants, so every
// Kind must appear. Both files are committed and verified fresh by
// `make verify-catalog` (part of `make check`).
package main

import (
	"bytes"
	"encoding/json"
	"flag"
	"fmt"
	"go/ast"
	"go/parser"
	"go/token"
	"io"
	"os"
	"sort"
	"strings"

	"corvus/internal/tool"
	_ "corvus/internal/tool/builtin" // side-effect registration
)

const (
	toolsHeader = `<!-- Generated by cmd/corvus-catalog (kind=tools). Do not edit by hand.
     Run ` + "`make tool-catalog`" + ` to regenerate. -->

# Tool Catalog

Every model-facing compile-time built-in tool: the name, description, and JSON
Schema the model receives, plus the host-side capability flags the agent loop
consults. Scope: ` + "`tool.Builtins()`" + ` (the builtin subpackage's init
registrations). Boot-wired tools — MCP/plugin adapters, session tools, memory,
skill, slash-command, install-source, and subagent delegation (` + "`task`" + `,
` + "`parallel_tasks`" + `, ` + "`fleet`" + `, ` + "`use_capability`" + `) — are
assembled at boot from configuration and are documented at their definition
sites.

Capability columns: ReadOnly (parallelisable without opt-in), PlanModeSafe
(allowed during plan mode), ConcurrencySafe (per-call parallel opt-in for
writers), Previewer (pre-approval file-change preview), SnipHint (custom
head/tail snip shape).

`
	eventsHeader = `<!-- Generated by cmd/corvus-catalog (kind=events). Do not edit by hand.
     Run ` + "`make event-map`" + ` to regenerate. -->

# Event Map

Every ` + "`event.Kind`" + ` the run loop and its extensions can emit, in source
declaration order with the source doc comment. A Kind missing from this table
fails ` + "`make verify-catalog`" + `, so a new event cannot be silently
undocumented. Producers and consumers live in the packages named in each
comment; the controller/sinks documented in ` + "`internal/event/event.go`" + `
consume the stream as a whole.

`
)

func main() {
	kind := flag.String("kind", "", "tools|events")
	eventSource := flag.String("event-source", "internal/event/event.go", "path to event.go for -kind events")
	flag.Parse()
	switch *kind {
	case "tools":
		genTools(os.Stdout)
	case "events":
		if err := genEvents(os.Stdout, *eventSource); err != nil {
			fmt.Fprintln(os.Stderr, "corvus-catalog:", err)
			os.Exit(1)
		}
	default:
		fmt.Fprintln(os.Stderr, "corvus-catalog: -kind must be tools or events")
		os.Exit(2)
	}
}

func genTools(w io.Writer) {
	fmt.Fprint(w, toolsHeader)
	tools := tool.Builtins()
	sort.Slice(tools, func(i, j int) bool { return tools[i].Name() < tools[j].Name() })
	for _, t := range tools {
		fmt.Fprintf(w, "## %s\n\n", t.Name())
		fmt.Fprintf(w, "%s\n\n", t.Description())
		flags := []string{}
		if t.ReadOnly() {
			flags = append(flags, "ReadOnly")
		}
		if c, ok := t.(tool.PlanModeClassifier); ok && c.PlanModeSafe() {
			flags = append(flags, "PlanModeSafe")
		}
		if _, ok := t.(tool.ConcurrencySafe); ok {
			flags = append(flags, "ConcurrencySafe")
		}
		if _, ok := t.(tool.Previewer); ok {
			flags = append(flags, "Previewer")
		}
		if _, ok := t.(tool.SnipHinter); ok {
			flags = append(flags, "SnipHint")
		}
		if len(flags) > 0 {
			fmt.Fprintf(w, "Capabilities: %s\n\n", strings.Join(flags, ", "))
		}
		var buf bytes.Buffer
		if err := json.Indent(&buf, t.Schema(), "", "  "); err == nil {
			fmt.Fprintf(w, "<details>\n<summary>JSON Schema</summary>\n\n```json\n%s\n```\n\n</details>\n\n", buf.String())
		}
	}
}

func genEvents(w io.Writer, source string) error {
	fset := token.NewFileSet()
	f, err := parser.ParseFile(fset, source, nil, parser.ParseComments)
	if err != nil {
		return fmt.Errorf("parse %s: %w", source, err)
	}
	var kindType *ast.TypeSpec
	for _, decl := range f.Decls {
		gd, ok := decl.(*ast.GenDecl)
		if !ok || gd.Tok != token.TYPE {
			continue
		}
		for _, spec := range gd.Specs {
			ts, ok := spec.(*ast.TypeSpec)
			if ok && ts.Name.Name == "Kind" {
				kindType = ts
			}
		}
	}
	if kindType == nil {
		return fmt.Errorf("type Kind not found in %s", source)
	}
	var names []struct {
		name, doc string
	}
	for _, decl := range f.Decls {
		gd, ok := decl.(*ast.GenDecl)
		if !ok || gd.Tok != token.CONST {
			continue
		}
		hasKind := false
		for _, spec := range gd.Specs {
			vs, ok := spec.(*ast.ValueSpec)
			if ok && vs.Type != nil {
				if ident, ok := vs.Type.(*ast.Ident); ok && ident.Name == "Kind" {
					hasKind = true
				}
			}
		}
		if !hasKind {
			continue
		}
		doc := gd.Doc.Text()
		for _, spec := range gd.Specs {
			vs := spec.(*ast.ValueSpec)
			name := vs.Names[0].Name
			d := ""
			if vs.Doc != nil {
				d = strings.TrimSpace(vs.Doc.Text())
			} else if len(vs.Names) == 1 && name == gd.Specs[0].(*ast.ValueSpec).Names[0].Name {
				d = strings.TrimSpace(doc)
			}
			names = append(names, struct{ name, doc string }{name, d})
		}
	}
	if len(names) == 0 {
		return fmt.Errorf("no Kind constants found in %s", source)
	}
	fmt.Fprint(w, eventsHeader)
	fmt.Fprint(w, "| Kind | Meaning |\n|---|---|\n")
	for _, n := range names {
		doc := strings.ReplaceAll(strings.TrimSpace(n.doc), "\n", " ")
		doc = strings.TrimPrefix(doc, n.name+" ")
		fmt.Fprintf(w, "| %s | %s |\n", n.name, doc)
	}
	return nil
}
